<template>
    <!-- Debugger Logs -->
    <SlideOver v-if="form.debug_mode" v-model="results.logsModal" title="Logs">
        <template #default>
            <Logs :logs="results.infoLogs" />
        </template>

        <template #buttons>
            <button class="btn-nav" @click="copyInfoLogs">
                <CheckIcon v-if="copiedLogsInfo" class="h-6 w-6" aria-hidden="true" />
                <ClipboardIcon v-if="!copiedLogsInfo && results.infoLogs.length != 0" class="h-6 w-6" aria-hidden="true" />
            </button>
            <input id="copy-info-logs" type="hidden" :value="results.infoLogs">
        </template>
    </SlideOver>

    <!-- Execution -->
    <div v-if="results.executing && !results.showResults" class="flex flex-col items-center justify-center select-none mt-[10%]">
        <div>
            <CircleProgressbar :progress="results.progressbar.current" />
        </div>

        <h3 v-if="!results.exception.error" class="mt-8 animate-pulse" v-text="remainingTimeText" />

        <div class="mt-8">
            <div class="mt-8">
                <UButton @click="cancel(Number($route.params.id))" color="gray" class="w-64 flex justify-center" icon="i-heroicons-no-symbol" size="sm" variant="solid" label="Cancel" :trailing="false" />
            </div>

            <a v-if="form.debug_mode && results.exception.error && results.progressbar.current !== 0" :href="logsUrl" class="flex justify-center items-center btn-secondary text-center mb-4 w-full">
                <DocumentDownloadIcon class="w-5 h-5 mr-2" />
                Debugging Logs
            </a>
        </div>

        <!-- exception  -->
        <div v-if="results.exception.error && results.executing" class="mx-auto container mt-8">
            <Exception :title="results.exception.error" :content="results.exception.traceback" mode="backtest" :debug-mode="form.debug_mode" :session-id="String(results.generalInfo.session_id)" v-model="exceptionReport" />
        </div>
    </div>

    <LayoutsSidebar else>
        <template #left>
            <!-- alert -->
            <div v-if="results.showResults && results.alert.message">
                <UAlert color="teal" icon="i-heroicons-check-circle" :title="results.alert.message" @close="results.alert.message = ''" :close-button="{ icon: 'i-heroicons-x-mark-20-solid', color: 'white', variant: 'link' }" />
            </div>

            <!-- Content -->
            <div v-if="!results.executing && !results.showResults">
                <Routes :form="form" :results="results" />

                <Divider class="mt-16" title="Options" />

                <div class="grid grid-cols-1 gap-6 mt-8">
                    <!-- debug mode -->
                    <ToggleButton v-model="form.debug_mode" title="Debug Mode" description="Logs every step of the execution. Very helpful for debugging your strategy but takes a lot longer to execute" />

                    <!-- export chart -->
                    <ToggleButton v-model="form.export_chart" title="Export Charts" description="Exports charts for your portfolio's daily balance." />

                    <!-- export trading view -->
                    <ToggleButton v-model="form.export_tradingview" title="Export Tradingview" description="Exports the executed trades in a format accepted by TradingView's Pine Editor. Useful to look at the executed orders on their chart." />

                    <!-- export full reports -->
                    <ToggleButton v-model="form.export_full_reports" title="Export QuantStats reports" description="Exports a HTML file generated by QuantStats library." />

                    <!-- export csv -->
                    <ToggleButton v-model="form.export_csv" title="Export CSV" description="Exports executed trades in a CSV format" />

                    <!-- export json -->
                    <ToggleButton v-model="form.export_json" title="Export JSON" description="Exports executed trades in a JSON format" />
                </div>

                <Divider class="mt-16" title="Duration" />

                <div class="flex items-center select-none flex-1 my-4">
                    <UInput v-model="form.start_date" type="date" variant="outline" size="xl" class="w-full mr-2" />

                    <UInput v-model="form.finish_date" type="date" variant="outline" size="xl" class="w-full ml-2" />
                </div>
            </div>

            <!-- Results -->
            <div v-if="results.showResults" class="w-full mx-auto">
                <div>
                    <Divider title="Routes" />
                    <MultipleValuesTable :data="results.routes_info" header />

                    <Divider v-if="results.hyperparameters.length" class="mt-16" title="Hyperparameters" />
                    <KeyValueTable v-if="results.hyperparameters.length" :data="results.hyperparameters" />

                    <Divider v-if="hasExecutedTrades" class="mt-16" title="Equity Curve" />
                    <EquityCurve v-if="hasExecutedTrades" :equity-curve="results.charts.equity_curve" />

                    <Divider v-if="hasExecutedTrades" class="mt-16" title="Performance" />
                    <KeyValueTable v-if="hasExecutedTrades" :data="results.metrics" />

                    <div v-if="!hasExecutedTrades" class="text-yellow-500 border-yellow-400 bg-yellow-50 dark:bg-gray-700 dark:text-yellow-400 mt-16 text-center text-2xl rounded border-2 border-dashed dark:border-gray-800 py-16 select-none">
                        No trades were executed via this strategy!
                    </div>
                </div>
            </div>
        </template>

        <template #right>
            <!-- Action Buttons -->
            <div v-if="!results.executing">
                <div v-if="results.showResults">
                    <button class="flex justify-center items-center btn-primary text-center mb-4 w-full" @click="rerun(Number($route.params.id))">
                        <RefreshIcon class="w-5 h-5 mr-2" />
                        Rerun
                    </button>

                    <button class="flex justify-center items-center btn-success text-center mb-4 w-full" @click="newBacktest(Number($route.params.id))">
                        <ReplyIcon class="w-5 h-5 mr-2" />
                        New session
                    </button>

                    <a v-if="form.debug_mode" :href="logsUrl" target="_blank" class="flex justify-center items-center btn-secondary text-center mb-4 w-full">
                        <DocumentDownloadIcon class="w-5 h-5 mr-2" />
                        Debugging Logs
                    </a>

                    <a v-if="form.export_chart && hasExecutedTrades" :href="legacyChartUrl" target="_blank" class="flex justify-center items-center btn-secondary text-center mb-4 w-full">
                        <DocumentDownloadIcon class="w-5 h-5 mr-2" />
                        Legacy Chart
                    </a>

                    <a v-if="form.export_full_reports && hasExecutedTrades" :href="fullReportsUrl" target="_blank" class="flex justify-center items-center btn-secondary text-center mb-4 w-full">
                        <DocumentDownloadIcon class="w-5 h-5 mr-2" />
                        QuantStats Report
                    </a>

                    <a v-if="form.export_csv && hasExecutedTrades" :href="csvUrl" target="_blank" class="flex justify-center items-center btn-secondary text-center mb-4 w-full">
                        <DocumentDownloadIcon class="w-5 h-5 mr-2" />
                        CSV
                    </a>

                    <a v-if="form.export_json && hasExecutedTrades" :href="jsonUrl" target="_blank" class="flex justify-center items-center btn-secondary text-center mb-4 w-full">
                        <DocumentDownloadIcon class="w-5 h-5 mr-2" />
                        JSON
                    </a>

                    <a v-if="form.export_tradingview && hasExecutedTrades" :href="tradingviewUrl" target="_blank" class="flex justify-center items-center btn-secondary text-center mb-4 w-full">
                        <DocumentDownloadIcon class="w-5 h-5 mr-2" />
                        TradingView Pine Editor
                    </a>

                    <hr class="my-8 border-2 dark:border-gray-600 rounded-full">

                    <KeyValueTableSimple :data="results.info" />
                </div>

                <div v-else>
                    <UButton @click="start(Number($route.params.id))" class="w-full flex justify-center" icon="i-heroicons-bolt" size="xl" variant="solid" label="Start" :trailing="false" />

                    <UButton @click="startInNewTab(Number($route.params.id))" class="w-full flex justify-center mt-4" color="gray" icon="i-heroicons-plus" size="xl" variant="solid" label="Start in a new tab" :trailing="false" />
                </div>
            </div>
        </template>
    </LayoutsSidebar>
</template>
  
<script setup lang="ts">
import { ref, computed, watchEffect } from 'vue'
import { useBacktestStore } from '@/stores/backtestState'
import { useAuthStore } from '@/stores/authState'
import helpers from '@/utils/helpers'
const props = defineProps<{
    form: BacktestForm;
    results: BacktestResults;
}>()

const exceptionReport = ref(false)
const copiedLogsInfo = ref(false)
const svgObject = ref({ display: false })

const backtestStore = useBacktestStore()

const { addTab, startInNewTab, start, cancel, rerun, newBacktest } = backtestStore

const auth_key = useAuthStore().authToken
const baseURL = ref(useRuntimeConfig().public.apiBaseUrl1)
const legacyChartUrl = computed(() => {
    let url = `/download/backtest/chart/${props.results.generalInfo.session_id}?token=${auth_key}`
    if (baseURL.value !== '/') {
        url = baseURL.value + url
    }
    return url
})

const logsUrl = computed(() => {
    let url = `/download/backtest/log/${props.results.generalInfo.session_id}?token=${auth_key}`
    if (baseURL.value !== '/') {
        url = baseURL.value + url
    }
    return url
})

const tradingviewUrl = computed(() => {
    let url = `/download/backtest/tradingview/${props.results.generalInfo.session_id}?token=${auth_key}`
    if (baseURL.value !== '/') {
        url = baseURL.value + url
    }
    return url
})

const fullReportsUrl = computed(() => {
    let url = `/download/backtest/full-reports/${props.results.generalInfo.session_id}?token=${auth_key}`
    if (baseURL.value !== '/') {
        url = baseURL.value + url
    }
    return url
})

const csvUrl = computed(() => {
    let url = `/download/backtest/csv/${props.results.generalInfo.session_id}?token=${auth_key}`
    if (baseURL.value !== '/') {
        url = baseURL.value + url
    }
    return url
})

const jsonUrl = computed(() => {
    let url = `/download/backtest/json/${props.results.generalInfo.session_id}?token=${auth_key}`
    if (baseURL.value !== '/') {
        url = baseURL.value + url
    }
    return url
})

const hasExecutedTrades = computed(() => props.results.metrics.length > 0)

const remainingTimeText = computed(() => helpers.remainingTimeText(props.results.progressbar.estimated_remaining_seconds))

watchEffect(() => {
    useBacktestStore().backtestForm = props.form
})

function copyInfoLogs() {
    navigator.clipboard.writeText(props.results.infoLogs)
    showNotification('success', 'Info copied successfully')
    copiedLogsInfo.value = true

    setTimeout(() => {
        copiedLogsInfo.value = false
    }, 3000)
}
</script>
  
  